######################################################################
# Automatically generated by qmake (3.0) ? 3? 28 02:22:52 2015
######################################################################

TEMPLATE = app
QT += widgets

TARGET = keyinput
INCLUDEPATH += .

# Input
HEADERS += \
	KeyView.h

SOURCES += \
	main.cpp \
	KeyView.cpp
